process.env.TZ='Europe/London';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const nodes=new Map();function node(id){if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',value:'',addEventListener(){}});return nodes.get(id);}
let mode='get',calls=0,release;
const context=vm.createContext({Date,Intl,Map,Set,Number,JSON,console,window:{zovaWorkspaceUrl:path=>path+"&workspace=7"},confirm:()=>true,document:{getElementById:node,querySelectorAll:()=>[]},fetch:async(url,options)=>{if(options?.method){calls++;if(mode==='hold')await new Promise(resolve=>release=resolve);return {ok:false,json:async()=>({detail:'Temporary failure'})};}return {ok:true,json:async()=>[]};}});
vm.runInContext(fs.readFileSync('nova/static/drafts.js','utf8'),context);
(async()=>{
 await context.loadSchedules();assert.match(node('scheduledJobs').innerHTML,/No approved deliveries/);assert.match(node('scheduledJobs').innerHTML,/Europe\/London/);
 const bounds=context.agendaBounds(0,new Date('2026-10-25T12:00:00Z'));assert.equal(bounds.start.getDay(),1);assert.equal(bounds.end.getDay(),1);assert.equal((bounds.end-bounds.start)/3600000,169);
 assert.throws(()=>context.scheduleLocalInstant('2026-03-29T01:30'),/does not exist/);assert.throws(()=>context.scheduleLocalInstant('2026-10-25T01:30'),/occurs twice/);assert.equal(context.scheduleLocalInstant('2026-09-29T12:00'),'2026-09-29T11:00:00.000Z');
 vm.runInContext(`scheduleAll=true;scheduleRows=[{id:1,draft_id:8,platform:'instagram',scheduled_at:'2026-09-29T11:00:00Z',status:'unknown'},{id:2,draft_id:9,platform:'x',scheduled_at:'2026-09-30T11:00:00Z',status:'pending'}]`,context);context.renderAgenda();assert.match(node('scheduledJobs').innerHTML,/workspace=7/);assert.match(node('scheduledJobs').innerHTML,/Outcome unconfirmed/);assert.match(node('scheduledJobs').innerHTML,/Pending at platform/);assert.doesNotMatch(node('scheduledJobs').innerHTML,/changeSchedule/);
 node('time-3').value='2026-10-01T12:00';mode='hold';const button={disabled:false};const first=context.changeSchedule(3,'reschedule',button);await context.changeSchedule(3,'reschedule',button);assert.equal(calls,1);release();await first;assert.equal(node('time-3').value,'2026-10-01T12:00');assert.match(node('scheduleStatus').textContent,/retained/);assert.equal(button.disabled,false);
 assert.match(context.scheduleCard({id:3,draft_id:3,platform:'instagram',status:'scheduled',scheduled_at:'2026-10-01T11:00:00Z'}),/value="2026-10-01T12:00"/);
 vm.runInContext(`scheduleHasMore=true;scheduleRows=Array.from({length:100},(_,i)=>({id:i,draft_id:i,platform:'x',status:'scheduled',scheduled_at:'2026-09-29T11:00:00Z'}))`,context);context.renderAgenda();assert.match(node('scheduledJobs').innerHTML,/latest 100/);
 let urls=[];context.fetch=async url=>{urls.push(url);return {ok:true,headers:{get:()=> 'false'},json:async()=>[]};};await context.moveAgendaWeek(1);assert.match(urls.at(-1),/from=.*&to=/);let query=new URL('https://test.invalid'+urls.at(-1));assert.equal(new Date(query.searchParams.get('from')).getDay(),1);await context.toggleAgendaRecords();assert.equal(urls.at(-1),'/api/schedules');
 const pending=[];context.fetch=url=>new Promise(resolve=>pending.push({url,resolve}));const older=context.moveAgendaWeek(1);const newer=context.moveAgendaWeek(1);pending[1].resolve({ok:true,headers:{get:()=> 'true'},json:async()=>[]});await newer;const rendered=node('scheduledJobs').innerHTML;pending[0].resolve({ok:true,headers:{get:()=> 'false'},json:async()=>[{id:99,draft_id:99,platform:'x',status:'unknown',scheduled_at:new Date().toISOString()}]});await older;assert.equal(node('scheduledJobs').innerHTML,rendered);assert.match(rendered,/view is incomplete/);
 console.log('Schedule agenda: 8 behavior groups passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
