const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=require('node:path').resolve(__dirname,'..');
function fixture(){
 const nodes=new Map();const node=id=>{if(!nodes.has(id))nodes.set(id,{value:'',textContent:'',innerHTML:'',style:{},addEventListener(){},focus(){},setSelectionRange(){},insertAdjacentHTML(){},scrollTo(){},close(){},remove(){}});return nodes.get(id);};
 const inputs=['x','instagram','facebook','tiktok'].map(value=>({value,checked:false,closest:()=>({classList:{toggle(){}}}),addEventListener(){}}));
 const document={getElementById:node,querySelector:()=>null,querySelectorAll:selector=>selector.includes('platform-check input:checked')?inputs.filter(n=>n.checked):selector.includes('.platform-check input')||selector==='.composer-platforms input'?inputs:[]};
 const ctx=vm.createContext({document,console,URLSearchParams,setTimeout:()=>0,clearTimeout(){},requestAnimationFrame:f=>f(),location:{search:'?draft=1',href:''},history:{replaceState(){}},window:{addEventListener(){},matchMedia:()=>({matches:false}),zovaWorkspaceUrl:url=>url+(url.includes('?')?'&':'?')+'workspace=7'},messages:[],inputs});
 for(const name of ['studio.js','studio-state.js','studio-publish.js'])vm.runInContext(fs.readFileSync(root+'/nova/static/'+name,'utf8'),ctx);
 vm.runInContext(`renderReadiness=()=>{};renderAttachments=()=>{};renderRecentPosts=()=>{};renderCanvas=()=>{};sizeComposer=()=>{};refreshPublicationResults=async()=>{};rememberSavedPost=()=>{};instagramFormat=()=> 'post';editingDraft=false;textHistory=[];publicationStates={};showMediaInspection=()=>{};addThinking=()=>{};removeThinking=()=>{};scrollChat=()=>{};addAssistantMessage=text=>messages.push(text);addUserMessage=text=>conversation.push({role:'user',content:text});`,ctx);
 return {ctx,node,inputs,run:s=>vm.runInContext(s,ctx)};
}
(async()=>{
 const f=fixture();f.ctx.row={id:1,revision:2,status:'draft',platforms:['x','instagram','facebook','tiktok'],variants:{x:{posts:['x']},instagram:{posts:['ig']},facebook:{posts:['fb']},tiktok:{posts:['tt']}},workspace:{selected_platforms:[]}};
 f.run('api=async()=>row');await f.run('loadRequestedDraft()');assert.equal(f.inputs.filter(n=>n.checked).length,4,'legacy empty selection restores actual versions');
 f.ctx.row.workspace={selected_platforms:[],platform_selection_explicit:true};await f.run('loadRequestedDraft()');assert.equal(f.inputs.filter(n=>n.checked).length,0,'intentional deselection survives reload');
 f.ctx.row.workspace={selected_platforms:['instagram'],platform_selection_explicit:true};await f.run('loadRequestedDraft()');assert.deepEqual(f.inputs.filter(n=>n.checked).map(n=>n.value),['instagram']);assert.equal(f.run('draftPayload().workspace.platform_selection_explicit'),true);
 f.ctx.row={id:2,platforms:['x'],variants:{x:{posts:['different draft']}},workspace:{selected_platforms:['x'],platform_selection_explicit:true}};await f.run('loadRequestedDraft()');assert.deepEqual(f.inputs.filter(n=>n.checked).map(n=>n.value),['x'],'draft switch restores its selection');
 const experience=fs.readFileSync(root+'/nova/static/studio-experience.js','utf8');f.run(experience.slice(experience.indexOf('function renderReadiness()'),experience.indexOf('function openReview()')));f.run('connectionData={};renderReadiness()');assert.equal(f.node('xFormat').hidden,false);assert.equal(f.node('instagramFormatControl').hidden,true);f.run("selectStudioPlatforms(['instagram'])");assert.equal(f.node('xFormat').hidden,true);assert.equal(f.node('instagramFormatControl').hidden,false);
 const stale=fixture();stale.node('brief').value='old request';stale.run('studioLoading=false;saveDraftNow=async()=>{}');let resolve;stale.ctx.deferred=new Promise(r=>resolve=r);stale.run('api=()=>deferred');const pending=stale.run('sendMessage()');await Promise.resolve();stale.run('workspaceEpoch++;currentDraftId=99;conversation=[]');stale.node('brief').value='new draft input';resolve({action:'answer',reply:'old answer'});await pending;assert.equal(stale.node('brief').value,'new draft input');assert.equal(stale.ctx.messages.length,0);
 const retry=fixture();retry.node('brief').value='make a post';retry.run(`studioLoading=false;currentDraftId=3;saveDraftNow=async()=>{};api=async url=>{if(url.includes('/plan'))return {action:'create',platforms:['x'],brief:'idea'};throw Error('Please retry');}`);await retry.run('sendMessage()');assert.equal(retry.node('brief').value,'make a post');retry.run("api=async()=>({action:'answer',reply:'A helpful proposal'})");await retry.run('sendMessage()');assert.equal(retry.run('conversation.filter(m=>m.role==="user").length'),1,'retry does not duplicate the user turn');
 const save=fixture();save.node('brief').value='a question';save.run(`studioLoading=false;currentDraftId=1;let saves=0;saveDraftNow=async()=>{if(++saves>1)throw Error('save outage')};api=async()=>({action:'answer',reply:'Ready answer'});`);await save.run('sendMessage()');assert.equal(save.node('brief').value,'','save error must not requeue an already answered request');assert.match(save.node('undoStatus').textContent,/not saved/);
 const copy=fixture();copy.run("variants={x:{posts:['retained']}};api=async()=>({id:22,revision:0});draftPayload=()=>({workspace:{}})");copy.ctx.button={};await copy.run("continueUnsubmitted(button,['x'])");assert.equal(copy.ctx.location.href,'/studio?draft=22&workspace=7');
 assert.equal(copy.run("mediaPreviewUrl('/media/preview/4')"),'/media/preview/4?workspace=7');assert.equal(copy.run("mediaPreviewUrl('https://cdn.example/media/preview/4')"),'https://cdn.example/media/preview/4');assert.match(copy.run("mediaPreview({url:'/media/preview/4',filename:'test',kind:'image'})"),/workspace=7/);
 const late=fixture();const publication=fs.readFileSync(root+'/nova/static/studio-publish.js','utf8');late.run(publication.split('\n').find(line=>line.startsWith('async function refreshPublicationResults()')));let reject;late.ctx.rejected=new Promise((_,r)=>reject=r);late.run('currentDraftId=1;api=()=>rejected');const check=late.run('refreshPublicationResults()');late.run('workspaceEpoch++;currentDraftId=2');reject(Error('old draft error'));await check;assert.equal(late.ctx.messages.length,0,'late publication failure cannot enter another conversation');
 const nav=fixture();nav.run(experience.slice(experience.indexOf('async function openSavedPost('),experience.indexOf("window.addEventListener('DOMContentLoaded',loadRecentPosts)")));nav.run(experience.slice(experience.indexOf('async function connectSelectedPlatform('),experience.indexOf('let recentPosts=[];')));nav.run("studioLoading=false;saveDraftNow=async()=>{};connectionPlatform='instagram'");nav.ctx.event={preventDefault(){}};nav.ctx.button={};await nav.run('openSavedPost(event,44)');assert.equal(nav.ctx.location.href,'/studio?draft=44&workspace=7');await nav.run('connectSelectedPlatform(button)');assert.equal(nav.ctx.location.href,'/connect/instagram?workspace=7');
 const comparison=fixture();comparison.run(experience.slice(experience.indexOf('async function compareSaved()'),experience.indexOf("document.querySelectorAll('.platform-check input').forEach")));let fail;comparison.ctx.waiting=new Promise((_,r)=>fail=r);comparison.run('currentDraftId=1;api=()=>waiting;threadHost=()=>{throw Error("stale comparison rendered")};');const comparing=comparison.run('compareSaved()');comparison.run('currentDraftId=2;workspaceEpoch++');fail(Error('old failure'));await comparing;
 f.run("currentPlatform='x';editingDraft=false;variants.instagram={posts:['caption']};instagramLabel=()=> 'Post';");const markup=f.run('draftWorkspace()');assert.match(markup,/role="group"/);assert.doesNotMatch(markup,/role="tab"/);
 const reviewing=fixture();reviewing.run("studioLoading=false;currentDraftId=1;variants={x:{posts:['review']}};saveDraftNow=async()=>{}");let rejectReview;reviewing.ctx.waiting=new Promise((_,r)=>rejectReview=r);reviewing.run('api=()=>waiting');const reviewingPromise=reviewing.run("requestPublishConfirmation('publish',null,['x'])");await Promise.resolve();reviewing.run('reviewEpoch++;currentDraftId=2');rejectReview(Error('old review error'));await reviewingPromise;assert.equal(reviewing.ctx.messages.length,0);
 console.log('Studio hydration, conditional controls, stale replies, retries, failed save and workspace copy passed');
})().catch(error=>{console.error(error);process.exitCode=1});
